### ISSUE TITLE
Redefinition of parameters

### ISSUE THREAD

**Issue by GuillaumeDievart** [tpunt/PHP7-Reference#10]
Hi Thomas,

I think you missed to talk about the redefinition of parameter not possible with the new engine .

Example:

``` php
function foo($a, $a) {}
// Fatal error: Redefinition of parameter $a in
```

For more information about it, you can check this article https://wiki.php.net/phpng in the incompatibilities section.

Thanks for your work !

**Comment by tpunt** [comment]
Hi Guillaume!

Yeah, there's a number of things missing, including (but not limited to):
- Some [new functions](http://php.net/manual/en/migration70.new-functions.php) (error_clear_last(), gmp_random_seed(), etc)
- The new `SessionUpdateTimestampHandlerInterface` interface
- [New constants](http://php.net/manual/en/migration70.constants.php) (such as PHP_INT_MIN)
- and so on...

This article simply covers the main features and changes in PHP 7 (for a more comprehensive coverage, see the [official PHP 7 migration guide](http://php.net/manual/en/migration70.php)). If you think this is worth mentioning though, then feel free to submit a PR and I'll merge it :)

-Tom

**Comment by GuillaumeDievart** [comment]
Hi,

ok, I think that the incompatibilities should be mentioned on PHP 7 reference. I'll do it with my weak english ...

Thanks !
