### ISSUE TITLE
Document substr() now returning an empty string instead of FALSE when the truncation happens on boundaries

### ISSUE THREAD

**Issue by nicolas-grekas** [tpunt/PHP7-Reference#12]
This is not a minor bc break, many libs/frameworks use `false !== substr()` in practice see
https://github.com/php/php-src/blob/php-7.0.0RC6/UPGRADING#L430

**Comment by tpunt** [comment]
Hi!

Strictly comparing `substr()`'s return value to `false` is not necessarily invalid still. `substr()` may still return false if:
- The start position is greater than the string: `substr("abc", 4)`
- The end position is a negative number that has an absolute value that is greater than the string length: `substr("abc", 0, -4)`
- The end position is less than 0, and the last position minus the start position plus the string length is less than 0: `substr("abc", 3, -1)`

`substr()` is a common function though, so a quick note in the Changes section may be helpful. I'll add that in soon.

Thanks,
Tom

**Comment by jrchamp** [comment]
I was thinking about this... It seems a bit dangerous for a framework to behave in a special way when `substr()` returns false, other than to say that the input was invalid. `substr()` should not be used to validate the string's length or provide other guarantees about the string's structure. Thinking long term, frameworks and libraries should only expect that `substr()` will return the substring of characters that meet the index criteria supplied. The fact that it returns false at all is PHP trying to help you realize that you made a mistake to even call the function with those parameters. An empty string in those cases would at least reduce the possible function return types.
