### ISSUE TITLE
PHP7 released!

### ISSUE THREAD

**Issue by tleb** [tpunt/PHP7-Reference#14]
> PHP 7 is set to be released on December 3rd, 2015.

Shouldn't this be modified?

**Comment by jessedc** [comment]
That's what Pull Requests are for.

**Comment by tleb** [comment]
I don't really know the project, I don't really know what it should be replaced with. I thought an issue would be a good place to discuss the replacement sentence.

Would this be fine?

> PHP 7 has been released on December 3rd, 2015.
