### ISSUE TITLE
list() function changes

### ISSUE THREAD

**Issue by p16** [tpunt/PHP7-Reference#16]
Hi @tpunt 
I was trying out the examples for the `list()` function and I was getting different results for 

``` PHP
$a = [1, 2];
list($a, $b) = $a;

// PHP <7 : $a = 1, $b = 2
// PHP 7: $a = 1, $b = null + "Undefined index 1"

$b = [1, 2];
list($a, $b) = $b;

// PHP <7 : $a = null + "Undefined index 0", $b = 2
// PHP 7: $a = 1, $b = 2
```

In my case I got

``` PHP
$a = [1, 2];
list($a, $b) = $a;

// PHP <7 : $a = 1, $b = 2
// PHP 7: $a = 1, $b = 2

$b = [1, 2];
list($a, $b) = $b;

// PHP <7: $a = null, $b = 2
// PHP 7: $a = 1, $b = 2
```

After checking the php versions and trying to understand why I got those different values, I found that in the documentation [it's stated](http://php.net/list) `Modification of the array during list() execution (e.g. using list($a, $b) = $b) results in undefined behavior.`

Given this discrepancies I've open a [bug on php.net](https://bugs.php.net/bug.php?id=71030) and they are looking into it. I've also done [some modifications](https://github.com/p16/PHP7-Reference/commit/8c5de4e2d6e42e12b6de91d0966dbd0532909231) and I will open a PR as soon as the matter is cleared :)

**Comment by tpunt** [comment]
Nice catch @p16. I'll wait for your PR to rectify this.
