### ISSUE TITLE
Clarity for Backward Compatibility and Enhancement Changes

### ISSUE THREAD

**Issue by otoby** [tpunt/PHP7-Reference#17]
There have been various misunderstanding of the section **Changes** and how it relates to _Backward Compatibility (BC)_ changes on PHP7 related forums. Could you please, see how you can make a distinction -- maybe via a separate section specifically for possible BC changes. This will be very helpful for reference purpose.

**Comment by otoby** [comment]
Also, please note that I see the BC lists below each related subject. My expectation is; as this is a reference documentation, there can be an easier way to find this kind of **essential** information without having to read all through the document.

**Comment by tpunt** [comment]
Hi,

The **Changes** section is there to list the differences from PHP 5.x and PHP 7.x that aren't really classed as features. The changes listed do not necessarily break BC, though some do - just like the new features do not necessarily break BC, though some do.

Where BC breaks have occurred, I've listed them under the **BC Breaks** heading for each feature/change. This allows readers to simply perform a `ctrl + f` for all **BC Breaks** sections, and they'd have the description of the feature/change right above it for further information.

Now, I could rearrange the document according to BC breaking features/changes, though I don't feel that this distinction is as helpful. In particular, some features _may_ cause a BC break, though they are highly unlikely to in reality (like the new IntlChar class). As a consequence of this, most new features and changes would be listed as breaking BC, and the document will seem rather disorganised.

Alternatively, I could create another category below **Changes** (titled **BC Breaks**) and create a canonical list of all BC breaks in PHP 7 (including those not mentioned in this article). This would act as a nice checklist that can be quickly referenced. If anyone reading this thinks this may be useful (though please bare in mind there's still the [official PHP 7 migration guide](http://php.net/manual/en/migration70.php)), then I'd be happy to do this.

Thanks,
Tom

**Comment by otoby** [comment]
@tpunt Having seen also the migration document, you all did a great Job. That document is detailed also.

Equally important, I think this repository should also include the suggested canonical list for completion.

Thanks.

**Comment by tpunt** [comment]
So life happened, and this didn't unfortunately... But still, I like the focus placed on the new features and changes for the reference articles in this repo.
